<h2> Extramarital affair Dataset</h2>
<h3>The dataset I chose is the affairs dataset that comes with Statsmodels. It
was derived from a survey of women in 1974 by Redbook magazine, in
which married women were asked about their participation in extramarital
affairs. More information about the study is available in a 1978 paper from
the Journal of Political Economy.
Description of Variables
The dataset contains 6366 observations of 9 variables.</h3>

In [5]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split 
from sklearn import metrics
from sklearn.model_selection import cross_val_score 

In [6]:
#load dataset
affairdata=sm.datasets.fair.load_pandas().data
affairdata.head()

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0            3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1            3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2            4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3            4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4            5.0  27.0          9.0       1.0        1.0  14.0         3.0   

   occupation_husb   affairs  
0              5.0  0.111111  
1              4.0  3.230769  
2              5.0  1.400000  
3              5.0  0.727273  
4              4.0  4.666666

In [9]:
#add "affair" column: 1 represents having affairs, 0 represents not 
affairdata['affair'] = (affairdata.affairs >0).astype(int)
affairdata.head()

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0            3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1            3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2            4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3            4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4            5.0  27.0          9.0       1.0        1.0  14.0         3.0   

   occupation_husb   affairs  affair  
0              5.0  0.111111       1  
1              4.0  3.230769       1  
2              5.0  1.400000       1  
3              5.0  0.727273       1  
4              4.0  4.666666       1

In [8]:
affairdata.groupby('affair').mean()
#We can see that on average, women who have affairs rate their marriages lower, which is to be expected. 

rate_marriage        age  yrs_married  children  religious       educ  \
affair                                                                          
0            4.329701  28.390679     7.989335  1.238813   2.504521  14.322977   
1            3.647345  30.537019    11.152460  1.728933   2.261568  13.972236   

        occupation  occupation_husb   affairs  
affair                                         
0         3.405286         3.833758  0.000000  
1         3.463712         3.884559  2.187243

In [10]:
#Let's take another look at the rate_marriage variable.
affairdata.groupby('rate_marriage').mean()

age  yrs_married  children  religious       educ  \
rate_marriage                                                           
1.0            33.823232    13.914141  2.308081   2.343434  13.848485   
2.0            30.471264    10.727011  1.735632   2.330460  13.864943   
3.0            30.008056    10.239174  1.638469   2.308157  14.001007   
4.0            28.856601     8.816905  1.369536   2.400981  14.144514   
5.0            28.574702     8.311662  1.252794   2.506334  14.399776   

               occupation  occupation_husb   affairs    affair  
rate_marriage                                                   
1.0              3.232323         3.838384  1.201671  0.747475  
2.0              3.327586         3.764368  1.615745  0.635057  
3.0              3.402820         3.798590  1.371281  0.550856  
4.0              3.420161         3.835861  0.674837  0.322926  
5.0              3.454918         3.892697  0.348174  0.181446

In [17]:
#create dataframes with an intercept column and dummy variables for occupation,occupation_husb
y, X = dmatrices('affair ~ rate_marriage + age +yrs_married + children + \
                  religious + educ +C(occupation) + C(occupation_husb)',affairdata, return_type="dataframe")
print(X.columns)

Index(['Intercept', 'C(occupation)[T.2.0]', 'C(occupation)[T.3.0]',
       'C(occupation)[T.4.0]', 'C(occupation)[T.5.0]', 'C(occupation)[T.6.0]',
       'C(occupation_husb)[T.2.0]', 'C(occupation_husb)[T.3.0]',
       'C(occupation_husb)[T.4.0]', 'C(occupation_husb)[T.5.0]',
       'C(occupation_husb)[T.6.0]', 'rate_marriage', 'age', 'yrs_married',
       'children', 'religious', 'educ'],
      dtype='object')


In [18]:
#The column names for the dummy variables are not good, so let's rename those-
#fix column names of X
X = X.rename(columns =
{'C(occupation)[T.2.0]':'occ_2',
'C(occupation)[T.3.0]':'occ_3',
'C(occupation)[T.4.0]':'occ_4',
'C(occupation)[T.5.0]':'occ_5',
'C(occupation)[T.6.0]':'occ_6',
'C(occupation_husb)[T.2.0]':'occ_husb_2',
'C(occupation_husb)[T.3.0]':'occ_husb_3',
'C(occupation_husb)[T.4.0]':'occ_husb_4',
'C(occupation_husb)[T.5.0]':'occ_husb_5',
'C(occupation_husb)[T.6.0]':'occ_husb_6'})

In [20]:
X.head()

Intercept  occ_2  occ_3  occ_4  occ_5  occ_6  occ_husb_2  occ_husb_3  \
0        1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   
1        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
2        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
3        1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
4        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   

   occ_husb_4  occ_husb_5  occ_husb_6  rate_marriage   age  yrs_married  \
0         0.0         1.0         0.0            3.0  32.0          9.0   
1         1.0         0.0         0.0            3.0  27.0         13.0   
2         0.0         1.0         0.0            4.0  22.0          2.5   
3         0.0         1.0         0.0            4.0  37.0         16.5   
4         1.0         0.0         0.0            5.0  27.0          9.0   

   children  religious  educ  
0       3.0        3.0  17.0  
1       3.0        1.0  14.0  
2       0.0        1.0  16.0  
3       4.0        3.0  16.0  
4       1.0        1.0  14.0

In [21]:
#We also need to flatten y into a 1-D array, so that scikit-learn will properly understand it as the response variable
#flatten y into a 1-D array
y = np.ravel(y)

In [22]:
#Let's go ahead and run logistic regression on the entire data set
model=LogisticRegression()
model=model.fit(X,y)

#check accuracy on training set
model.score(X,y)

C:\Users\Vishnu\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.7251021049324536

In [23]:
#73% accuracy seems good, but what's the null error rate?
#what percentage had affairs?
y.mean()

0.3224945020420987

In [27]:
#Let's examine the coefficients
import pandas as pd
pd.DataFrame(list(zip(X.columns,np.transpose(model.coef_))))

0                        1
0       Intercept     [1.3834936641888063]
1           occ_2    [0.06111361968611139]
2           occ_3     [0.3829748766511305]
3           occ_4     [0.1213508651926668]
4           occ_5     [0.7740386701893878]
5           occ_6    [0.23691875676710808]
6      occ_husb_2    [0.30252067161672236]
7      occ_husb_3     [0.4406801215505912]
8      occ_husb_4    [0.25547144698354385]
9      occ_husb_5     [0.2716195415727841]
10     occ_husb_6    [0.23977286250906274]
11  rate_marriage    [-0.6818690785325475]
12            age  [-0.058781332859346405]
13    yrs_married    [0.10721324069122934]
14       children   [0.014922263153725506]
15      religious    [-0.3735670903979894]
16           educ   [0.013424000317644874]

In [30]:
from sklearn.linear_model import LogisticRegression 
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size= 0.25, random_state = 355)
model2=LogisticRegression()
model2.fit(x_train,y_train)

C:\Users\Vishnu\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
#We now need to predict class labels for the test set. We will also generate the class probabilities
#predict class labels for the test
y_pred=model2.predict(x_test)
print(y_pred)

[1. 0. 0. ... 1. 1. 0.]


In [32]:
#generate class probabilities
probs=model2.predict_proba(x_test)
print(probs)

[[0.45895101 0.54104899]
 [0.69064114 0.30935886]
 [0.88640854 0.11359146]
 ...
 [0.39288193 0.60711807]
 [0.18160886 0.81839114]
 [0.53783073 0.46216927]]


In [33]:
#evaluation metrics
print(metrics.accuracy_score(y_test,y_pred))
print(metrics.roc_auc_score(y_test,probs[:,1]))

0.7167085427135679
0.7356075849144318


In [34]:
#We can also see the confusion matrix and a classification report with other metrics
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))

[[967 117]
 [334 174]]
              precision    recall  f1-score   support

         0.0       0.74      0.89      0.81      1084
         1.0       0.60      0.34      0.44       508

    accuracy                           0.72      1592
   macro avg       0.67      0.62      0.62      1592
weighted avg       0.70      0.72      0.69      1592



In [36]:
#Model Evaluation Using Cross-Validation-
#Now let's try 10-fold cross-validation, to see if the accuracy holds up more rigorously.
scores=cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=10)
print(scores)

C:\Users\Vishnu\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Vishnu\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-r

[0.72370487 0.69858713 0.73940345 0.70800628 0.71428571 0.72684458
 0.72798742 0.70754717 0.75       0.75314465]


C:\Users\Vishnu\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Vishnu\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-r

In [37]:
print(scores.mean())

0.7249511270400758


In [39]:
model.predict_proba(np.array([[1,0,0,1,0,0,1,0,0,0,0,3,25,3,1,4,16]]))

array([[0.77586125, 0.22413875]])